/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MatchState = IDL.Record({
  'overs' : IDL.Nat,
  'runs' : IDL.Nat,
  'wickets' : IDL.Nat,
  'balls' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getSavedMatchState' : IDL.Func([], [MatchState], ['query']),
  'saveMatchState' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MatchState = IDL.Record({
    'overs' : IDL.Nat,
    'runs' : IDL.Nat,
    'wickets' : IDL.Nat,
    'balls' : IDL.Nat,
  });
  
  return IDL.Service({
    'getSavedMatchState' : IDL.Func([], [MatchState], ['query']),
    'saveMatchState' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };