/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Team = IDL.Record({ 'name' : IDL.Text, 'score' : IDL.Nat });
export const Time = IDL.Int;
export const Match = IDL.Record({
  'team1' : Team,
  'team2' : Team,
  'overs' : IDL.Nat,
  'date' : Time,
  'balls' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'saveMatch' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Team = IDL.Record({ 'name' : IDL.Text, 'score' : IDL.Nat });
  const Time = IDL.Int;
  const Match = IDL.Record({
    'team1' : Team,
    'team2' : Team,
    'overs' : IDL.Nat,
    'date' : Time,
    'balls' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'saveMatch' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };